// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// spde_neuronized_basic_one_gene_cpp
Rcpp::List spde_neuronized_basic_one_gene_cpp(const arma::vec& y_g, const arma::mat& B, const arma::vec& lambda, const int N, const int BURN, const int thin, const int mh_per_k, const double kappa_g, const double alpha_g, const double xi_g0, const double nu_g0, const double eta_g0_sq, const double m_g0, const double gamma_g0, const double a_g0, const double b_g0, const int prior_type, const double lam1, const double lam2, const double lam3, const double xi_prop_sd, const int tau2_g_update, double mu_g, double sigma2_g, double tau2_g, arma::vec xi_g, arma::vec omega_g);
RcppExport SEXP _GeoSVG3D_spde_neuronized_basic_one_gene_cpp(SEXP y_gSEXP, SEXP BSEXP, SEXP lambdaSEXP, SEXP NSEXP, SEXP BURNSEXP, SEXP thinSEXP, SEXP mh_per_kSEXP, SEXP kappa_gSEXP, SEXP alpha_gSEXP, SEXP xi_g0SEXP, SEXP nu_g0SEXP, SEXP eta_g0_sqSEXP, SEXP m_g0SEXP, SEXP gamma_g0SEXP, SEXP a_g0SEXP, SEXP b_g0SEXP, SEXP prior_typeSEXP, SEXP lam1SEXP, SEXP lam2SEXP, SEXP lam3SEXP, SEXP xi_prop_sdSEXP, SEXP tau2_g_updateSEXP, SEXP mu_gSEXP, SEXP sigma2_gSEXP, SEXP tau2_gSEXP, SEXP xi_gSEXP, SEXP omega_gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_g(y_gSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type BURN(BURNSEXP);
    Rcpp::traits::input_parameter< const int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const int >::type mh_per_k(mh_per_kSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa_g(kappa_gSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_g(alpha_gSEXP);
    Rcpp::traits::input_parameter< const double >::type xi_g0(xi_g0SEXP);
    Rcpp::traits::input_parameter< const double >::type nu_g0(nu_g0SEXP);
    Rcpp::traits::input_parameter< const double >::type eta_g0_sq(eta_g0_sqSEXP);
    Rcpp::traits::input_parameter< const double >::type m_g0(m_g0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma_g0(gamma_g0SEXP);
    Rcpp::traits::input_parameter< const double >::type a_g0(a_g0SEXP);
    Rcpp::traits::input_parameter< const double >::type b_g0(b_g0SEXP);
    Rcpp::traits::input_parameter< const int >::type prior_type(prior_typeSEXP);
    Rcpp::traits::input_parameter< const double >::type lam1(lam1SEXP);
    Rcpp::traits::input_parameter< const double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< const double >::type lam3(lam3SEXP);
    Rcpp::traits::input_parameter< const double >::type xi_prop_sd(xi_prop_sdSEXP);
    Rcpp::traits::input_parameter< const int >::type tau2_g_update(tau2_g_updateSEXP);
    Rcpp::traits::input_parameter< double >::type mu_g(mu_gSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_g(sigma2_gSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_g(tau2_gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xi_g(xi_gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type omega_g(omega_gSEXP);
    rcpp_result_gen = Rcpp::wrap(spde_neuronized_basic_one_gene_cpp(y_g, B, lambda, N, BURN, thin, mh_per_k, kappa_g, alpha_g, xi_g0, nu_g0, eta_g0_sq, m_g0, gamma_g0, a_g0, b_g0, prior_type, lam1, lam2, lam3, xi_prop_sd, tau2_g_update, mu_g, sigma2_g, tau2_g, xi_g, omega_g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeoSVG3D_spde_neuronized_basic_one_gene_cpp", (DL_FUNC) &_GeoSVG3D_spde_neuronized_basic_one_gene_cpp, 27},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeoSVG3D(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
