# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spde_neuronized_basic_one_gene_cpp <- function(y_g, B, lambda, N, BURN, thin, mh_per_k, kappa_g, alpha_g, xi_g0, nu_g0, eta_g0_sq, m_g0, gamma_g0, a_g0, b_g0, prior_type, lam1, lam2, lam3, xi_prop_sd, tau2_g_update, mu_g, sigma2_g, tau2_g, xi_g, omega_g) {
    .Call(`_GeoSVG3D_spde_neuronized_basic_one_gene_cpp`, y_g, B, lambda, N, BURN, thin, mh_per_k, kappa_g, alpha_g, xi_g0, nu_g0, eta_g0_sq, m_g0, gamma_g0, a_g0, b_g0, prior_type, lam1, lam2, lam3, xi_prop_sd, tau2_g_update, mu_g, sigma2_g, tau2_g, xi_g, omega_g)
}

